from django.urls import path

from . import views

urlpatterns = [
    path("students/", views.students, name="students"),
    path("students.html", views.students, name="students-html"),
    path("student-dashboard.html", views.student_dashboard, name="student-dashboard-html"),
    path("teacher-dashboard.html", views.teacher_dashboard, name="teacher-dashboard-html"),
    path("student-details.html", views.student_details, name="student-details-html"),
    path("add-student.html", views.add_student, name="add-student-html"),
    path("edit/<str:slug>/", views.edit_student, name="edit-student-slug"),
    path("students/dashboard/", views.student_dashboard, name="student-dashboard"),
    path("teachers/dashboard/", views.teacher_dashboard, name="teacher-dashboard"),
    path("students/complete-profile/", views.complete_student_profile, name="complete_student_profile"),
    path("teachers/complete-profile/", views.complete_teacher_profile, name="complete_teacher_profile"),
    path("students/view/", views.student_details, name="student-details"),
    path("students/view/<int:id>/", views.view_student, name="view_student"),
    path("students/add/", views.add_student, name="add-student"),
    path("students/edit/", views.edit_student, name="edit-student"),
    path("students/edit/<int:id>/", views.edit_student, name="edit_student"),
    path("students/delete/<int:id>/", views.delete_student, name="delete_student_id"),
    path("students/approve/<int:id>/", views.approve_student, name="approve_student"),
    path("students/reject/<int:id>/", views.reject_student, name="reject_student"),
    path("delete/<str:slug>/", views.delete_student, name="delete_student"),
    path("teachers/", views.teacher_list, name="teacher_list"),
    path("teachers.html", views.teacher_list, name="teachers-html"),
    path("teachers/add/", views.add_teacher, name="add_teacher"),
    path("add-teacher.html", views.add_teacher, name="add-teacher-html"),
    path("teachers/view/", views.teacher_detail, name="teacher_detail_blank"),
    path("teachers/view/<int:id>/", views.teacher_detail, name="teacher_detail"),
    path("teacher-details.html", views.teacher_detail, name="teacher-details-html"),
    path("teachers/edit/<int:id>/", views.edit_teacher, name="edit_teacher"),
    path("edit-teacher.html", views.teacher_list, name="edit-teacher-html"),
    path("teachers/delete/<int:id>/", views.delete_teacher, name="delete_teacher"),
    path("teachers/approve/<int:id>/", views.approve_teacher, name="approve_teacher"),
    path("teachers/reject/<int:id>/", views.reject_teacher, name="reject_teacher"),
    path("departments/", views.department_list, name="department_list"),
    path("departments.html", views.department_list, name="departments-html"),
    path("departments/add/", views.add_department, name="add_department"),
    path("add-department.html", views.add_department, name="add-department-html"),
    path("departments/edit/<int:id>/", views.edit_department, name="edit_department"),
    path("edit-department.html", views.department_list, name="edit-department-html"),
    path("departments/delete/<int:id>/", views.delete_department, name="delete_department"),
    path("subjects/", views.subject_list, name="subject_list"),
    path("subjects.html", views.subject_list, name="subjects-html"),
    path("subjects/add/", views.add_subject, name="add_subject"),
    path("add-subject.html", views.add_subject, name="add-subject-html"),
    path("subjects/edit/<int:id>/", views.edit_subject, name="edit_subject"),
    path("edit-subject.html", views.subject_list, name="edit-subject-html"),
    path("subjects/delete/<int:id>/", views.delete_subject, name="delete_subject"),
    path("", views.student_list, name="student_list"),
    path("add/", views.add_student, name="add_student")
]
